version: '3'

networks:
  database-net:

services:
  server:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=fetcher
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - database-net
    links:
      - db:db
    entrypoint: ["npm", "run", "start"]
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=fetcher
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5665:5432"
    networks:
      - database-net
      - default
